### ISSUE TITLE
Add scantailor-advanced

### ISSUE THREAD

**Issue by yodatak** [flathub/org.scantailor.ScanTailor#1]
Hi it can be usefull to add too scantailor-advanced in another repo because it add some feature and is more updated ( 17 jul 2018 )
https://forum.diybookscanner.org/viewtopic.php?f=21&t=3455
https://github.com/4lex4/scantailor-advanced#scan-tailor-advanced

**Comment by Unrud** [comment]
https://github.com/flathub/flathub/pull/1011
